### PR TITLE
Implement basic Spotify feature/widget

### LINKED ISSUE #245: Implement basic youtube feature/side widget

### PR DESCRIPTION
**Pull request by bche536**
Added spotify side widget, need to implement addNewWidget() functionality to backend

### CODE REVIEW

**Comment by OverCry** [comment]
Whats with WidgetSpotifyPlayer.module.css? Its an empty file right now. Did you forget to use it or something?

**Review by OverCry — APPROVED** [review]
Looking at the changes, it seems like only WidgetSpotifyPlayer.jsx may have an issue. However, comparing it to existing widgets, it looks good to me

**Comment by bche536** [comment]
css file is there just for completion sake as extra styling has not yet been added as it is all overwritten by a higher level css file

It is missing backend functionality rn

**Comment by bche536** [comment]
pause on this PR, change of direction

**Comment by bche536** [comment]
aniket is making his own branch to implement this

**Pull request closed without merging**
