### PR TITLE
Closes #48: Created a base React JS app using the 'Create-React-App' NPM module

### LINKED ISSUE #48: Create base React JS application using Create-React-App
**Is your feature request related to a problem? Please describe.**
There is no base react application to base the project on. One needs to be initialised.

**Describe the solution you'd like**
Use the NPM `create-react-app` module to initialise a base React JS project to work from.

**Describe alternatives you've considered**
Creating a React JS app from scratch, which would be inefficient. Using other tools, which would go against consensus formed to used create-react-app.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by JChamberlain28**
Closes #48 

This PR adds a base React JS app to the repo to form the basis of the frontend implementation.
This PR also adds a folder structure for use by frontend development on the project.

### CODE REVIEW

**Comment by JChamberlain28** [comment]
Note: this PR is well over the 200 lines guideline due to the boilerplate code created by 'create-react-app'

**Comment by JChamberlain28** [comment]
Before running the app, ensure you run "npm install" to get all dependencies. These are not included due to .gitignore settings.

**Review by RawiriHohepa — APPROVED** [review]
Looks good to me

**Review by ysway — APPROVED** [review]
Good job

**Pull request merged**
