### PR TITLE
Closes #141: Created Menu, updated routes for dashboard widgets

### LINKED ISSUE #141: Create Menu to Choose Dashboard Views
**Is your feature request related to a problem? Please describe.**
As an end user I want to open a menu from any page to choose what page I want to see

**Describe the solution you'd like**
A menu openable from any page that switches between the journal view and any full-screen / dashboard widgets

**Describe alternatives you've considered**
Have no menu - the user would have to navigate to the desired URL manually

**Additional context**
Blocked by #92

### PR DESCRIPTION
**Pull request by RawiriHohepa**
Closes #141 

## Proposed Changes

- Added a dropdown menu to the top bar to choose between journal and each of the full screen widgets
- Changed the routing of App to always render TopBar
- Removed the test prefix from paths of full screen widgets routes in App

image

### CODE REVIEW

**Review by lhuijser — APPROVED** [review]
This looks great to me! Thanks for implementing this :)

**Comment by Benjamin-Piper** [comment]
Found this error in my console. Investigating now.

image

**EDIT:** NVM Looks like [Material UI is not up-to-date with React](https://stackoverflow.com/questions/61220424/material-ui-drawer-finddomnode-is-deprecated-in-strictmode)

**Review by Benjamin-Piper — APPROVED** [review]
Cool, I approve :) Something we should note is that the TopBar causes at least my screen to scroll with fullscreen widgets (e.g. in DashboardCalendar, we'll need to fix that magic number).

**Comment by RawiriHohepa** [comment]
> Cool, I approve :) Something we should note is that the TopBar causes at least my screen to scroll with fullscreen widgets (e.g. in DashboardCalendar, we'll need to fix that magic number).

Yeah I noticed that too, I'll make a bug report

**Pull request merged**
