### PR TITLE
Feature text widget state functionality

### LINKED ISSUE #46: Text widget (Journal / Daily View) - functionality with dummy data
**Is your feature request related to a problem? Please describe.**
The text widget is not functional and requires work to allow it to read and save text data.

**Describe the solution you'd like**
Implement a way to type, autosave and retrieve text. This should use dummy data and storage to ensure correct functionality.

**Describe alternatives you've considered**
Not implementing functionality. This would lead to an unusable widget that serves no purpose.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by JChamberlain28**
Closes #46

## Proposed Changes

- added useState that keeps track of the most up to date text content of the Journal Text widget (autosave)
- added a Jest test file with a test to check if the component is being re-rendered with the new text state upon triggering a state update

### CODE REVIEW

**Review by a-158w — APPROVED** [review]
LGTM

**Comment by milkyway404** [comment]
> Delete this line once you've reviewed the [Contribution Guidelines!](https://github.com/UOA-SE701-Group3-2021/3Lancers/wiki/Contribution-Guidelines#pull-requests)
> 
> Closes #46
> 
> ## Proposed Changes
> * added useState that keeps track of the most up to date text content of the Journal Text widget (autosave)
> * added a Jest test file with a test to check if the component is being re-rendered with the new text state upon triggering a state update

Please delete the initial line

**Comment by JChamberlain28** [comment]
> > Delete this line once you've reviewed the [Contribution Guidelines!](https://github.com/UOA-SE701-Group3-2021/3Lancers/wiki/Contribution-Guidelines#pull-requests)
> > Closes #46
> > ## Proposed Changes
> > 
> > * added useState that keeps track of the most up to date text content of the Journal Text widget (autosave)
> > * added a Jest test file with a test to check if the component is being re-rendered with the new text state upon triggering a state update
> 
> Please delete the initial line

just noticed that as u commented. done

**Review by milkyway404 — APPROVED** [review]
LGTM. Cloned and checked due to concerns about package-lock.json changes, but everything works fine :)

**Pull request merged**
