### PR TITLE
Added Logo and improved styling

### LINKED ISSUE #19: Lo-fi design of the product logo
**Is your feature request related to a problem? Please describe.**
As a frontend developer, I want a rough idea of the product logo I'm implementing, so that I can begin coding the logic.

**Describe the solution you'd like**
A lo-fi prototype of the product logo

**Describe alternatives you've considered**
Start coding right away - would result in conflict further down the road.

**Additional context**
None.

### LINKED ISSUE #20: Hi-fi design of the product logo
**Is your feature request related to a problem? Please describe.**
As a frontend developer, I want a detailed prototype of the product logo I'm implementing, so that I can finalise the styling and logic.

**Describe the solution you'd like**
A hi-fi prototype of the product logo.

**Describe alternatives you've considered**
Start coding right away - would result in conflict further down the road.
Come up with own styling - would stand out from the UI.

**Additional context**
None.

### LINKED ISSUE #242: [FEAT] Improve theme and styling of the To-Do app
**Is your feature request related to a problem? Please describe.**
The theme and styling of the web app is too basic and simple.

**Describe the solution you'd like**
Add better theme and styling to the existing frontend code. 

**Describe alternatives you've considered**
Not changing anything and keep original design.

**Additional context**
May involve pulling in issues #19 and #20

### PR DESCRIPTION
**Pull request by DavidHuangz**
Closes https://github.com/UOA-SE701-Group3-2021/3Lancers/issues/242 , #20 , #19

## Proposed Changes
Added Logo and improved styling for habit and To Do pages.

### CODE REVIEW

**Review by Alxjlv — APPROVED** [review]
Wow that looks way better! 

My only complaint would be that the logo and the purple clash a bit - maybe change the purple accents to something more neutral?

**Comment by DavidHuangz** [comment]
> Wow that looks way better!
> 
> My only complaint would be that the logo and the purple clash a bit - maybe change the purple accents to something more neutral?

image
Would this look better by following only white and purple theme?

This website gives a lot of different designs we can choose from as well: https://editor.freelogodesign.org/?category=0&companyName=Telos

**Review by jemimahmartinez — COMMENTED** [review]
Looks great! To add to the icon issue, white and purple definitely looks a lot better.

Also, would it be okay if we vertically centred 'Telos' too?

**Comment by DavidHuangz** [comment]
> Looks great! To add to the icon issue, white and purple definitely looks a lot better.
> 
> Also, would it be okay if we vertically centred 'Telos' too?

Alright, done all: 
image

**Review by jemimahmartinez — APPROVED** [review]
Great work, LGTM!👌

**Pull request merged**
