### PR TITLE
Closes #189: removed console.log from method stubs as it violates ESLint rules

### LINKED ISSUE #189: Undesired warnings messages of frontend codes
**Describe the bug**
When running the frontend app, there are many linter warning messages in the terminal, and there are warnings of unchanged files in the *GitHub Actions / Run Frontend Tests and Linter* as well

**To Reproduce**
`npm start`
Run GitHub Actions Tester

**Expected behaviour**
clean and no warnings and no errors

**Screenshots**
image

### PR DESCRIPTION
**Pull request by JChamberlain28**
Closes #189 

## Proposed Changes

- Removed console.log() occurrences from empty method stubs in TopBar.jsx in `telos-frontend/src/components/top-bar`
- These print statements are not needed, empty method stubs are acceptable

### CODE REVIEW

**Review by ODE-BOY — COMMENTED** [review]
I think it is good to go. All Lint checks and tests have passed for me.
I did however get this error.
image
I'm not sure if could be a problem on my end, or if it could be dismissed entirely since the tests did pass.

**Comment by JChamberlain28** [comment]
> I think it is good to go. All Lint checks and tests have passed for me.
> I did however get this error.
> image
> I'm not sure if could be a problem on my end, or if it could be dismissed entirely since the tests did pass.

Do you have any more information about the error or stack trace (or anything indicating where the error occurred)? The changes made were to remove print statements, so I believe this error is not related to this PR but could be a more widespread occurance.

**Review by ysway — APPROVED** [review]
Looks good for me, no more warnings/errors on my side

**Comment by ODE-BOY** [comment]
> 
> 
> > I think it is good to go. All Lint checks and tests have passed for me.
> > I did however get this error.
> > image
> > I'm not sure if could be a problem on my end, or if it could be dismissed entirely since the tests did pass.
> 
> Do you have any more information about the error or stack trace (or anything indicating where the error occurred)? The changes made were to remove print statements, so I believe this error is not related to this PR but could be a more widespread occurance.

I just retested without the changes and the error is still present so its must be unrelated to your PR and likely as an issue on my local. I give it my thumbs up.

**Review by milkyway404 — APPROVED** [review]
Changes are small and looks valid. I agree that no console logs are needed, just causes unnecessary lint warnings.

**Pull request merged**
