### PR TITLE
Implement basic Calendar Journal design

### LINKED ISSUE #70: Calendar Widget (Journal/Daily) - Implement design
**Is your feature request related to a problem? Please describe.**
There is currently no implementation of the calendar widget for the journal/daily design that is being implemented.

**Describe the solution you'd like**
I want there to be a visual representation of the calendar widget using react.

**Describe alternatives you've considered**
N/A

**Additional context**
The calendar widget for the journal/daily view will only be designed. The functionality will not be implemented

### PR DESCRIPTION
**Pull request by maheknangia**
Closes #70 

## Proposed Changes

- Implemented the basic calendar widget design
- Widget doesn't have any functionality currently
- Widget does not use any dummy data

Visual Representation of widget:
Screen Shot 2021-03-18 at 8 10 49 PM

### CODE REVIEW

**Comment by ysway** [comment]
Could you solve the conflict

**Review by ysway — APPROVED** [review]
Looks good for me now

**Comment by milkyway404** [comment]
Could you please include images?

**Comment by maheknangia** [comment]
I've added an image to the PR description

**Review by milkyway404 — APPROVED** [review]

**Pull request merged**
