### PR TITLE
Closes #28: Backend readme

### LINKED ISSUE #28: Backend Readme
**Is your request related to a problem? Please describe.**
Yes. There is no documentation for the backend.

**Describe the solution you'd like**
I will create a readme.md in our folder

**Describe alternatives you've considered**
N/A

### PR DESCRIPTION
**Pull request by kyzh0**
Closes #28

Backend readme writeup

### CODE REVIEW

**Review by ODE-BOY — COMMENTED** [review]
Having never run a backend test, I could easily follow all the instructions in this new README, download the prerequisites and run and test the backend. 
The only part I found unclear was ending the Local Mongoose instance. Including the 'control C' command in the readme could assist any newcomers who are unfamiliar with the procedure.
Apart from that I'd say this is a clear and concise readme.

**Review by werer9 — APPROVED** [review]
Really nicely written README, I was about to write it myself but glad you have done such a nice job :)

**Review by flexzy — COMMENTED** [review]
Nice readme, really easy to follow and the steps are exactly what we need for the backend to start up. 
Do we currently have document(s) somewhere of our API and db schema? If we do, could be good to add in a quick link in this readme for anyone wanting to use our API.

**Comment by kyzh0** [comment]
> Nice readme, really easy to follow and the steps are exactly what we need for the backend to start up.
> Do we currently have document(s) somewhere of our API and db schema? If we do, could be good to add in a quick link in this readme for anyone wanting to use our API.

Good idea, thanks! Links added.

**Comment by kyzh0** [comment]
> Having never run a backend test, I could easily follow all the instructions in this new README, download the prerequisites and run and test the backend.
> The only part I found unclear was ending the Local Mongoose instance. Including the 'control C' command in the readme could assist any newcomers who are unfamiliar with the procedure.
> Apart from that I'd say this is a clear and concise readme.

Thanks! I've added that in.

**Review by khal745 — APPROVED** [review]
Great work, LGTM! Addressed previous comments and also fantastic job with the API documentation and schema in the wiki!

**Pull request merged**
