### PR TITLE
Closes #31: Generating backend app structure with basic dependencies.

### LINKED ISSUE #31: Generate Backend App Structure - NodeJS/Express
**Is your feature request related to a problem? Please describe.**
We need an initial structure for the backend so that developers can easily understand and extend it with the required functionality.

**Describe the solution you'd like**
Generate an initial set of directories and files that can launch a basic Express app, and contains a layout to add in routes and models in a simple and understandable way.

**Describe alternatives you've considered**
We considered developing using different tech stacks eg. using Java (JaxRS), but ultimately decided on NodeJS/Express as it keeps a single language across the repo (including frontend) and the MERN stack is a popular and standard tech stack.

**Additional context**
We need this initial commit before other backend features can be implemented

### PR DESCRIPTION
**Pull request by khal745**
Closes #31 

Created basic boilerplate for the backend of the app. Sets up some minimal dependencies (Express, Mongoose, Jest) as well as a directory structure with placeholder files and a simple test to show the testing framework is working.

To setup the server, change directory into the `telos-backend` directory and run the command `npm start`
Browsing to `localhost:3001` should show a basic message. Browswing to `localhost:3001/api` should return a basic JSON response (to verify the server and routing works)

A simple placeholder test has been set up, and it can be run by executing `npm run test`

### CODE REVIEW

**Comment by JChamberlain28** [comment]
This is minor but ensuring you use a : not a - for separating the issue from the PR title would be good

**Comment by JChamberlain28** [comment]
I have also included "Closes #31" in your description to ensure GitHub detects the related issue

**Comment by kyzh0** [comment]
Couple comments on package structure:
1. models directory should be directly under src/
2. two index.js files and src/routes/api directory not needed
3. perhaps rename server.js to app.js

**Review by kyzh0 — COMMENTED** [review]
Couple comments on package structure:

models directory should be directly under src/
two index.js files and src/routes/api directory not needed
perhaps rename server.js to app.js

**Review by kyzh0 — APPROVED** [review]
LGTM

**Review by flexzy — APPROVED** [review]
LGTM

**Review by werer9 — APPROVED** [review]
lgtm

**Pull request merged**
