### PR TITLE
add dashboard calendar design

### LINKED ISSUE #80: Calendar (dashboard / fullscreen) - Implement design
**Is your feature request related to a problem? Please describe.**
Currently there is no implementation of the calendar widget in dashboard/fullscreen view.

**Describe the solution you'd like**
I want there to be a react component for the implementation of the dashboard/fullscreen calendar widget. Only design, no functionality.

**Describe alternatives you've considered**
- Instead of a fullscreen calendar, add some sort of redirect to a calendar app like google calendar and integrate the user data with it.
- Use another calendar app that the user already uses as an iframe on the web-app.

**Additional context**
Currently thinking of using the below options:
- https://fullcalendar.io/
- https://www.npmjs.com/package/react-big-calendar
- https://www.npmjs.com/package/react-calendar

### PR DESCRIPTION
**Pull request by hsingh124**
## Proposed Changes
**This PR is with reference to the issue https://github.com/UOA-SE701-Group3-2021/3Lancers/issues/80.**
- Added the basic design for the dashboard calendar view.
- Changed default css to match the app's design.

**Here are some screenshots of the widget:** 
Screen Shot 2021-03-20 at 12 27 36 PM
Screen Shot 2021-03-20 at 12 27 45 PM
Screen Shot 2021-03-20 at 12 28 05 PM

### CODE REVIEW

**Review by RawiriHohepa — APPROVED** [review]
Looks good, nice job finding that calendar library!

**Comment by Benjamin-Piper** [comment]
@hsingh124 Looks good! Small thing: have you tried adding `cursor: pointer` styling to the buttons? I reckon it would look nicer. Otherwise good job!

**Comment by hsingh124** [comment]
> cursor: pointer

Good point. Will add that in the next PR, thanks!

**Review by a-158w — APPROVED** [review]
LGTM

**Pull request merged**
